In [ ]:
import pandas as pd
import numpy as np

In [ ]:
a = np.arange(0,20,5,dtype='int64')
a

array([ 0,  5, 10, 15])

In [ ]:
a.shape

(4,)

In [ ]:
a = a.reshape(2,2)
a

array([[ 0,  5],
       [10, 15]])

In [ ]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [ ]:
np.c_[a,b]

array([[ 0,  5,  5,  6],
       [10, 15,  7,  8]])

In [ ]:
np.r_[a,b]

array([[ 0,  5],
       [10, 15],
       [ 5,  6],
       [ 7,  8]])

In [ ]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr[1:3,0]

array([3, 6])

In [ ]:
arr[1:3,:]

array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr[1:3,1:]

array([[4, 5],
       [7, 8]])

In [ ]:
arr[2:,:2]

array([[ 6,  7],
       [ 9, 10]])

In [ ]:
def avg(a):
  return np.mean(a)

df = pd.DataFrame(np.arange(12).reshape(4,3))
df

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [ ]:
df.apply(avg,axis=0)

0    4.5
1    5.5
2    6.5
dtype: float64

In [ ]:
df.apply(avg,axis=1)

0     1.0
1     4.0
2     7.0
3    10.0
dtype: float64

In [ ]:
df.apply(lambda x:np.mean(x),axis=0)

0    4.5
1    5.5
2    6.5
dtype: float64

In [ ]:
df.apply(lambda x:x.max()-x.min(),axis=1)

0    2
1    2
2    2
3    2
dtype: int64

In [ ]:
df = df.astype('str')
df.applymap(lambda x:x*2)

0     1     2
0  00    11    22
1  33    44    55
2  66    77    88
3  99  1010  1111

In [ ]:
'2'*6

'222222'